# Form implementation generated from reading ui file 'actualizacionFecha.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#!/usr/bin/env python
# -*- coding: utf-8 -*-
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmActualizarFecha(object):
    def setupUi(self, frmActualizarFecha):
        frmActualizarFecha.setObjectName("frmActualizarFecha")
        frmActualizarFecha.resize(486, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmActualizarFecha.sizePolicy().hasHeightForWidth())
        frmActualizarFecha.setSizePolicy(sizePolicy)
        frmActualizarFecha.setMaximumSize(QtCore.QSize(486, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/Iconos/fecha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmActualizarFecha.setWindowIcon(icon)
        self.brnConfirmar = QtWidgets.QPushButton(frmActualizarFecha)
        self.brnConfirmar.setGeometry(QtCore.QRect(200, 290, 101, 23))
        self.brnConfirmar.setObjectName("brnConfirmar")
        self.dtpFecha = QtWidgets.QCalendarWidget(frmActualizarFecha)
        self.dtpFecha.setGeometry(QtCore.QRect(90, 50, 312, 183))
        self.dtpFecha.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.dtpFecha.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.dtpFecha.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.SingleLetterDayNames)
        self.dtpFecha.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.dtpFecha.setObjectName("dtpFecha")
        self.dtpHora = QtWidgets.QTimeEdit(frmActualizarFecha)
        self.dtpHora.setGeometry(QtCore.QRect(250, 250, 118, 22))
        self.dtpHora.setObjectName("dtpHora")
        self.lblHoraPartido = QtWidgets.QLabel(frmActualizarFecha)
        self.lblHoraPartido.setGeometry(QtCore.QRect(130, 250, 91, 20))
        self.lblHoraPartido.setObjectName("lblHoraPartido")
        self.lblFechaPartido = QtWidgets.QLabel(frmActualizarFecha)
        self.lblFechaPartido.setGeometry(QtCore.QRect(90, 10, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblFechaPartido.setFont(font)
        self.lblFechaPartido.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblFechaPartido.setObjectName("lblFechaPartido")

        self.retranslateUi(frmActualizarFecha)
        QtCore.QMetaObject.connectSlotsByName(frmActualizarFecha)

    def retranslateUi(self, frmActualizarFecha):
        _translate = QtCore.QCoreApplication.translate
        frmActualizarFecha.setWindowTitle(_translate("frmActualizarFecha", "Formulario de Actualización de Fecha"))
        self.brnConfirmar.setText(_translate("frmActualizarFecha", "Confirmar"))
        self.lblHoraPartido.setText(_translate("frmActualizarFecha", "Hora del partido:"))
        self.lblFechaPartido.setText(_translate("frmActualizarFecha", "Fecha del partido"))
