#!/usr/bin/env python
# -*- coding: utf-8 -*-
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmPremios(object):
    def setupUi(self, frmPremios):
        frmPremios.setObjectName("frmPremios")
        frmPremios.resize(600, 459)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPremios.sizePolicy().hasHeightForWidth())
        frmPremios.setSizePolicy(sizePolicy)
        frmPremios.setMaximumSize(QtCore.QSize(600, 492))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/Iconos/premio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        frmPremios.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(frmPremios)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 600, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(600, 491))
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnCambiarPrecio = QtWidgets.QPushButton(self.tab)
        self.btnCambiarPrecio.setGeometry(QtCore.QRect(220, 280, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCambiarPrecio.setFont(font)
        self.btnCambiarPrecio.setObjectName("btnCambiarPrecio")
        self.lblImgPrecio = QtWidgets.QLabel(self.tab)
        self.lblImgPrecio.setGeometry(QtCore.QRect(250, 20, 91, 91))
        self.lblImgPrecio.setText("")
        self.lblImgPrecio.setPixmap(QtGui.QPixmap("../Icons/Iconos/precio2.png"))
        self.lblImgPrecio.setScaledContents(True)
        self.lblImgPrecio.setObjectName("lblImgPrecio")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(130, 140, 261, 25))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblPrecioActual = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblPrecioActual.setFont(font)
        self.lblPrecioActual.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPrecioActual.setObjectName("lblPrecioActual")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPrecioActual)
        self.lblPrecioActualColocar = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblPrecioActualColocar.setFont(font)
        self.lblPrecioActualColocar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPrecioActualColocar.setObjectName("lblPrecioActualColocar")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lblPrecioActualColocar)
        self.widget1 = QtWidgets.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(120, 210, 334, 31))
        self.widget1.setObjectName("widget1")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setHorizontalSpacing(15)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblNuevoPrecio = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblNuevoPrecio.setFont(font)
        self.lblNuevoPrecio.setObjectName("lblNuevoPrecio")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNuevoPrecio)
        self.txtNuevoPrecio = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtNuevoPrecio.setFont(font)
        self.txtNuevoPrecio.setObjectName("txtNuevoPrecio")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNuevoPrecio)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/Iconos/precio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.jtbPremiosDisponibles = QtWidgets.QWidget()
        self.jtbPremiosDisponibles.setObjectName("jtbPremiosDisponibles")
        self.lblImgPremio = QtWidgets.QLabel(self.jtbPremiosDisponibles)
        self.lblImgPremio.setGeometry(QtCore.QRect(230, 40, 131, 131))
        self.lblImgPremio.setText("")
        self.lblImgPremio.setPixmap(QtGui.QPixmap("../Icons/Iconos/premio2.png"))
        self.lblImgPremio.setScaledContents(True)
        self.lblImgPremio.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblImgPremio.setObjectName("lblImgPremio")
        self.widget2 = QtWidgets.QWidget(self.jtbPremiosDisponibles)
        self.widget2.setGeometry(QtCore.QRect(190, 200, 221, 150))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblPremiosDisponibles = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblPremiosDisponibles.setFont(font)
        self.lblPremiosDisponibles.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPremiosDisponibles.setObjectName("lblPremiosDisponibles")
        self.verticalLayout.addWidget(self.lblPremiosDisponibles)
        self.lblMontoDisponible = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblMontoDisponible.setFont(font)
        self.lblMontoDisponible.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMontoDisponible.setObjectName("lblMontoDisponible")
        self.verticalLayout.addWidget(self.lblMontoDisponible)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icons/Iconos/cofre.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.jtbPremiosDisponibles, icon2, "")
        self.jtbAgregarPremio = QtWidgets.QWidget()
        self.jtbAgregarPremio.setObjectName("jtbAgregarPremio")
        self.btnRegistrar = QtWidgets.QPushButton(self.jtbAgregarPremio)
        self.btnRegistrar.setGeometry(QtCore.QRect(280, 250, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.lblImgPremio_2 = QtWidgets.QLabel(self.jtbAgregarPremio)
        self.lblImgPremio_2.setGeometry(QtCore.QRect(250, 50, 111, 101))
        self.lblImgPremio_2.setText("")
        self.lblImgPremio_2.setPixmap(QtGui.QPixmap("../Icons/Iconos/premio3.png"))
        self.lblImgPremio_2.setScaledContents(True)
        self.lblImgPremio_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblImgPremio_2.setObjectName("lblImgPremio_2")
        self.layoutWidget = QtWidgets.QWidget(self.jtbAgregarPremio)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 190, 301, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblMontoAgregar = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblMontoAgregar.setFont(font)
        self.lblMontoAgregar.setObjectName("lblMontoAgregar")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblMontoAgregar)
        self.txtMontoAgregar = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMontoAgregar.setFont(font)
        self.txtMontoAgregar.setObjectName("txtMontoAgregar")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMontoAgregar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Icons/Iconos/agregar3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.jtbAgregarPremio, icon3, "")
        self.jtbEliminarPremio = QtWidgets.QWidget()
        self.jtbEliminarPremio.setObjectName("jtbEliminarPremio")
        self.lblImgEliminarPremio = QtWidgets.QLabel(self.jtbEliminarPremio)
        self.lblImgEliminarPremio.setGeometry(QtCore.QRect(260, 60, 91, 81))
        self.lblImgEliminarPremio.setText("")
        self.lblImgEliminarPremio.setPixmap(QtGui.QPixmap("../Icons/Iconos/eliminarpremio.png"))
        self.lblImgEliminarPremio.setScaledContents(True)
        self.lblImgEliminarPremio.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblImgEliminarPremio.setObjectName("lblImgEliminarPremio")
        self.layoutWidget_2 = QtWidgets.QWidget(self.jtbEliminarPremio)
        self.layoutWidget_2.setGeometry(QtCore.QRect(180, 180, 261, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(25)
        self.formLayout_3.setVerticalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblPremio2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPremio2.setFont(font)
        self.lblPremio2.setObjectName("lblPremio2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPremio2)
        self.txtMontoQuitar = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtMontoQuitar.setFont(font)
        self.txtMontoQuitar.setObjectName("txtMontoQuitar")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtMontoQuitar)
        self.btnQuitarMonto = QtWidgets.QPushButton(self.jtbEliminarPremio)
        self.btnQuitarMonto.setGeometry(QtCore.QRect(260, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnQuitarMonto.setFont(font)
        self.btnQuitarMonto.setObjectName("btnQuitarMonto")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Icons/Iconos/eliminar2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.jtbEliminarPremio, icon4, "")

        self.retranslateUi(frmPremios)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPremios)

    def retranslateUi(self, frmPremios):
        _translate = QtCore.QCoreApplication.translate
        frmPremios.setWindowTitle(_translate("frmPremios", "Premios"))
        self.btnCambiarPrecio.setText(_translate("frmPremios", "Cambiar Precio"))
        self.lblPrecioActual.setText(_translate("frmPremios", "Precio Actual ($):"))
        self.lblPrecioActualColocar.setText(_translate("frmPremios", "0"))
        self.lblNuevoPrecio.setText(_translate("frmPremios", "Precio Nuevo ($): "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmPremios", "Definir Precio Participación"))
        self.lblPremiosDisponibles.setText(_translate("frmPremios", "Premio Disponible"))
        self.lblMontoDisponible.setText(_translate("frmPremios", "$25"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jtbPremiosDisponibles), _translate("frmPremios", "Monto Disponible"))
        self.btnRegistrar.setText(_translate("frmPremios", "Registrar"))
        self.lblMontoAgregar.setText(_translate("frmPremios", "Monto a agregar:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jtbAgregarPremio), _translate("frmPremios", "Agregar Monto"))
        self.lblPremio2.setText(_translate("frmPremios", "Monto a quitar:"))
        self.btnQuitarMonto.setText(_translate("frmPremios", "Quitar Monto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jtbEliminarPremio), _translate("frmPremios", "Quitar Monto"))
